### ISSUE TITLE
Bug report : Cannot start an instance with Advanced Backups and Hexerei

### ISSUE THREAD

**Issue by NielsPilgaard** [MommyHeather/AdvancedBackups#24] opened 2023-09-29 17:55 UTC
**Describe the bug**

> Exception in thread "main" java.lang.module.ResolutionException: Modules advancedbackups and com.google.gson export package com.google.gson.stream to module hexerei

I wasn't able to see this error until I toggled the option to open the output log when Minecraft starts.

**To Reproduce**
1. Make a tiny modpack with Advanced Backups (+dependencies) and Hexerei (+dependencies)
2. Launch it
3. See error

**Expected behavior**
For the game to start

**Screenshots**

**Versioning (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version(s): 1.19.2
 - Modloader(s): Forge
 - Mod Version: 43.2.14

Entire log, from the output window of the Minecraft launcher: https://gist.github.com/NielsPilgaard/85fe51af1c1d32fc95e9fe6a16d76ca3

**Comment by MommyHeather** [comment] 2023-09-29 20:43
Thank you, I'll look into this... just to check, do you experience this with an older version? 
[AdvancedBackups-forge-1.19-2.1.zip](https://github.com/MommyHeather/AdvancedBackups/files/12771592/AdvancedBackups-forge-1.19-2.1.zip)

I've attached version 2.1 - unavailable on curseforge, so if you wanted to grab from there you'd need 2.0.
If the issue doesn't occur here, it basically tells me exactly what's at fault.

(I likely won't be able to try a repro today, but will do so tomorrow)

**Comment by MommyHeather** [comment] 2023-09-29 22:20
Nevermind. Confirmed repro, potentially a confirmed fix...

**Comment by MommyHeather** [comment] 2023-09-29 22:30
Running some final tests but should be fixed.

**Comment by MommyHeather** [comment] 2023-09-29 22:40
Yep, all fixed. Actions for curseforge + modrinth will be running now.

**Comment by MommyHeather** [comment] 2023-09-29 22:43
Curseforge awaiting approval, modrinth.. approved already? Let me know if you're having any further issues, but none should be encountered. 

New mod version is 2.1.3.

**Comment by MommyHeather** [comment] 2023-09-29 23:33
Okay, all files *except* 1.16 got flagged for manual review for some reason... That could take a few days. 


In the meantime, all files are available from modrinth or the Build All Mod Jars workflow.

**Comment by NielsPilgaard** [comment] 2023-09-30 16:42
Thanks for the swift fix 😊

**Comment by MommyHeather** [comment] 2023-09-30 16:44
> Thanks for the swift fix 😊

No problem! Thanks for the report haha

**Comment by MommyHeather** [comment] 2023-10-01 16:18
Seems a bunch of older files have retroactively been put into manual review too... No word from CF about it, but I think it's due to the fact that 2.0 and newer write batch scripts - given the recent mods that were downnloading and running malicious scripts, I imagine they're manually reviewing all mods that also interact with bat scripts?

Do you want me to keep you updated on this? @NielsPilgaard

**Comment by NielsPilgaard** [comment] 2023-10-01 16:34
Yes please :)

**Comment by MommyHeather** [comment] 2023-10-01 22:27
Small update - the older files have been reverified, seems they weren't meant to be put into manual review - as for the newer ones, apparently one of the classes failed to decompile. We've confirmed the class *can* be decompiled so I'll see where it goes from there

**Comment by MommyHeather** [comment] 2023-10-02 10:59
All approved! Closing as everything should be resolved now. @NielsPilgaard

**Closed by MommyHeather** 2023-10-02 10:59 UTC
Labels: bug
